require_relative 'config/environment'

desc "Loads a console"
task :console do
    Pry.start
end

desc "say hello to mod1"
task :say_hi do 
    puts "Hello Mod 1!"
end

desc "set up database tables"
task :db_setup do 
    # HEREDOC
    book_sql = <<-SQL

    CREATE TABLE IF NOT EXISTS books (id INTEGER PRIMARY KEY, title TEXT, author_id INTEGER);
    SQL
    author_sql = <<-SQL
        CREATE TABLE IF NOT EXISTS authors (id INTEGER PRIMARY KEY, name TEXT);
    SQL
    DB.execute(book_sql)
    DB.execute(author_sql)    
end